
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35N9vuS0j1QDjMFB2F-RRstpqBh7BQGA',
    authDomain: 'trabalho-400a6.firebaseapp.com',
    projectId: 'trabalho-400a6',
    storageBucket: 'trabalho-400a6.firebasestorage.app',
    messagingSenderId: '78630774757',
    appId: '1:78630774757:web:5d51460e793603feb6b10c'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPUwOxy_XJhEbTCfEnkzy5D9EAteU4CI',
    appId: '1:78630774757:android:5b4413f06133e924b6b10c',
    messagingSenderId: '78630774757',
    projectId: 'trabalho-400a6',
    storageBucket: 'trabalho-400a6.firebasestorage.app'
  );
}
